insert into ingredient (name, type) values ('Flour Tortilla', 1)
insert into ingredient (name, type) values ('Corn Tortilla', 1)
insert into ingredient (name, type) values ('Ground Beef', 2)
insert into ingredient (name, type) values ('Carnitas', 2)
insert into ingredient (name, type) values ('Diced Tomatoes', 3)
insert into ingredient (name, type) values ('Lettuce', 3)
insert into ingredient (name, type) values ('Cheddar', 4)
insert into ingredient (name, type) values ('Monterrey Jack', 4)
insert into ingredient (name, type) values ('Salsa', 0)
insert into ingredient (name, type) values ('Sour Cream', 0)